name: CI
on:
  push: { branches: [master] }
  pull_request: { branches: [master] }

jobs:
  build:
    name: Build, lint, and test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install and audit dependencies
        run: yarn install --frozen-lockfile --audit

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci

      - name: Build
        run: yarn build

      - name: Code Climate
        if: startsWith(matrix.os, 'ubuntu')
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
